"""empty message

Revision ID: d90f6c8e8f12
Revises: af27a1f63fc1
Create Date: 2024-11-13 19:33:21.481339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90f6c8e8f12'
down_revision = 'af27a1f63fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('session')
    op.drop_table('poll')
    op.drop_table('user')
    op.drop_table('item')
    op.drop_table('movies')
    op.drop_table('ticket')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_confirmed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_delivered', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('items')
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('items', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('paid')
        batch_op.drop_column('status')
        batch_op.drop_column('date_delivered')
        batch_op.drop_column('date_confirmed')
        batch_op.drop_column('date_created')
        batch_op.drop_column('notes')
        batch_op.drop_column('order')
        batch_op.drop_column('user')

    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sessionId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('numberOfTickets', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confirmTickets', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bought', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ticket_pkey')
    )
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('count', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='movies_pkey')
    )
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trending', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vendor'], ['user.id'], name='item_vendor_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('poll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sessionId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movie', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movieConfirm', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tlk', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('probability', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('startDate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='poll_pkey')
    )
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sessionId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
